from typing import Literal
from .env_args import EnvArg


class EnvManager:
    def __init__(self, path: str = ..., mode: Literal["w", "r"] = "r"): ...
    def write(self, data: dict[str, EnvArg]) -> None: ...
    def load(self) -> dict: ...
    def __enter__(self) -> EnvManager: ...
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None: ...


def load_pyenv(path: str = ...) -> dict: ...

    